-- test01
INSERT INTO ACCOUNT
      (EMAIL, FIRSTNAME, LASTNAME, STATUS, ADDR1, ADDR2, CITY, STATE, ZIP, COUNTRY, PHONE, USERID)
    VALUES
      ('test01@jadecross.com', 'test01', 'test01', NULL, '1111',  '1111', '1111', '1111', '1111', '1111', '1111', 'test01');
INSERT INTO PROFILE (LANGPREF, FAVCATEGORY, MYLISTOPT, BANNEROPT, USERID)
    VALUES ('english', 'FISH', '0', '0', 'test01');
INSERT INTO SIGNON (PASSWORD,USERNAME)
    VALUES ('jadecross', 'test01');
	
-- test02
INSERT INTO ACCOUNT
      (EMAIL, FIRSTNAME, LASTNAME, STATUS, ADDR1, ADDR2, CITY, STATE, ZIP, COUNTRY, PHONE, USERID)
    VALUES
      ('test02@jadecross.com', 'test02', 'test02', NULL, '1111',  '1111', '1111', '1111', '1111', '1111', '1111', 'test02');
INSERT INTO PROFILE (LANGPREF, FAVCATEGORY, MYLISTOPT, BANNEROPT, USERID)
    VALUES ('english', 'FISH', '0', '0', 'test02');
INSERT INTO SIGNON (PASSWORD,USERNAME)
    VALUES ('jadecross', 'test02');
	
-- test03
INSERT INTO ACCOUNT
      (EMAIL, FIRSTNAME, LASTNAME, STATUS, ADDR1, ADDR2, CITY, STATE, ZIP, COUNTRY, PHONE, USERID)
    VALUES
      ('test03@jadecross.com', 'test03', 'test03', NULL, '1111',  '1111', '1111', '1111', '1111', '1111', '1111', 'test03');
INSERT INTO PROFILE (LANGPREF, FAVCATEGORY, MYLISTOPT, BANNEROPT, USERID)
    VALUES ('english', 'FISH', '0', '0', 'test03');
INSERT INTO SIGNON (PASSWORD,USERNAME)
    VALUES ('jadecross', 'test03');
	
-- test04
INSERT INTO ACCOUNT
      (EMAIL, FIRSTNAME, LASTNAME, STATUS, ADDR1, ADDR2, CITY, STATE, ZIP, COUNTRY, PHONE, USERID)
    VALUES
      ('test04@jadecross.com', 'test04', 'test04', NULL, '1111',  '1111', '1111', '1111', '1111', '1111', '1111', 'test04');
INSERT INTO PROFILE (LANGPREF, FAVCATEGORY, MYLISTOPT, BANNEROPT, USERID)
    VALUES ('english', 'FISH', '0', '0', 'test04');
INSERT INTO SIGNON (PASSWORD,USERNAME)
    VALUES ('jadecross', 'test04');
	
-- test05
INSERT INTO ACCOUNT
      (EMAIL, FIRSTNAME, LASTNAME, STATUS, ADDR1, ADDR2, CITY, STATE, ZIP, COUNTRY, PHONE, USERID)
    VALUES
      ('test05@jadecross.com', 'test05', 'test05', NULL, '1111',  '1111', '1111', '1111', '1111', '1111', '1111', 'test05');
INSERT INTO PROFILE (LANGPREF, FAVCATEGORY, MYLISTOPT, BANNEROPT, USERID)
    VALUES ('english', 'FISH', '0', '0', 'test05');
INSERT INTO SIGNON (PASSWORD,USERNAME)
    VALUES ('jadecross', 'test05');
	
-- test06
INSERT INTO ACCOUNT
      (EMAIL, FIRSTNAME, LASTNAME, STATUS, ADDR1, ADDR2, CITY, STATE, ZIP, COUNTRY, PHONE, USERID)
    VALUES
      ('test06@jadecross.com', 'test06', 'test06', NULL, '1111',  '1111', '1111', '1111', '1111', '1111', '1111', 'test06');
INSERT INTO PROFILE (LANGPREF, FAVCATEGORY, MYLISTOPT, BANNEROPT, USERID)
    VALUES ('english', 'FISH', '0', '0', 'test06');
INSERT INTO SIGNON (PASSWORD,USERNAME)
    VALUES ('jadecross', 'test06');
	
-- test07
INSERT INTO ACCOUNT
      (EMAIL, FIRSTNAME, LASTNAME, STATUS, ADDR1, ADDR2, CITY, STATE, ZIP, COUNTRY, PHONE, USERID)
    VALUES
      ('test07@jadecross.com', 'test07', 'test07', NULL, '1111',  '1111', '1111', '1111', '1111', '1111', '1111', 'test07');
INSERT INTO PROFILE (LANGPREF, FAVCATEGORY, MYLISTOPT, BANNEROPT, USERID)
    VALUES ('english', 'FISH', '0', '0', 'test07');
INSERT INTO SIGNON (PASSWORD,USERNAME)
    VALUES ('jadecross', 'test07');
	
-- test08
INSERT INTO ACCOUNT
      (EMAIL, FIRSTNAME, LASTNAME, STATUS, ADDR1, ADDR2, CITY, STATE, ZIP, COUNTRY, PHONE, USERID)
    VALUES
      ('test08@jadecross.com', 'test08', 'test08', NULL, '1111',  '1111', '1111', '1111', '1111', '1111', '1111', 'test08');
INSERT INTO PROFILE (LANGPREF, FAVCATEGORY, MYLISTOPT, BANNEROPT, USERID)
    VALUES ('english', 'FISH', '0', '0', 'test08');
INSERT INTO SIGNON (PASSWORD,USERNAME)
    VALUES ('jadecross', 'test08');
	
-- test09
INSERT INTO ACCOUNT
      (EMAIL, FIRSTNAME, LASTNAME, STATUS, ADDR1, ADDR2, CITY, STATE, ZIP, COUNTRY, PHONE, USERID)
    VALUES
      ('test09@jadecross.com', 'test09', 'test09', NULL, '1111',  '1111', '1111', '1111', '1111', '1111', '1111', 'test09');
INSERT INTO PROFILE (LANGPREF, FAVCATEGORY, MYLISTOPT, BANNEROPT, USERID)
    VALUES ('english', 'FISH', '0', '0', 'test09');
INSERT INTO SIGNON (PASSWORD,USERNAME)
    VALUES ('jadecross', 'test09');
	
-- test10
INSERT INTO ACCOUNT
      (EMAIL, FIRSTNAME, LASTNAME, STATUS, ADDR1, ADDR2, CITY, STATE, ZIP, COUNTRY, PHONE, USERID)
    VALUES
      ('test10@jadecross.com', 'test10', 'test10', NULL, '1111',  '1111', '1111', '1111', '1111', '1111', '1111', 'test10');
INSERT INTO PROFILE (LANGPREF, FAVCATEGORY, MYLISTOPT, BANNEROPT, USERID)
    VALUES ('english', 'FISH', '0', '0', 'test10');
INSERT INTO SIGNON (PASSWORD,USERNAME)
    VALUES ('jadecross', 'test10');
	